# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

import datetime
import decimal
import sys

# global imports for type checking
from builtins import bool as _bool
from builtins import float as _float
from builtins import int as _int
from builtins import str as _str
from typing import (
    TYPE_CHECKING,
    Any,
    Callable,
    ClassVar,
    Dict,
    Generic,
    Iterable,
    Iterator,
    List,
    Mapping,
    NoReturn,
    Optional,
    Sequence,
    Set,
    Tuple,
    Type,
    TypeVar,
    Union,
    cast,
    overload,
)

from typing_extensions import Literal, TypedDict

LiteralString = str
# -- template http.py.jinja --
from ._sync_http import HTTP as HTTP
from ._sync_http import Response as Response
from ._sync_http import client as client
