# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

import datetime
import decimal
import sys

# global imports for type checking
from builtins import bool as _bool
from builtins import float as _float
from builtins import int as _int
from builtins import str as _str
from typing import (
    TYPE_CHECKING,
    Any,
    Callable,
    ClassVar,
    Dict,
    Generic,
    Iterable,
    Iterator,
    List,
    Mapping,
    NoReturn,
    Optional,
    Sequence,
    Set,
    Tuple,
    Type,
    TypeVar,
    Union,
    cast,
    overload,
)

from typing_extensions import Literal, TypedDict

LiteralString = str
# -- template partials.py.jinja --
from pydantic import validator

# users can modify relational types which are then namespaced to partials.
# so we have to import ourselves in order to resolve forward references
from . import actions, bases, enums, fields, models, partials, types

# fmt: on
