repos:
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: python pre-commit-npm.py run prettier:fix
        types_or: [javascript, json]
        language: system
        pass_filenames: false

      - id: eslint
        name: eslint
        entry: python pre-commit-npm.py run lint:es:fix
        types_or: [javascript, json]
        language: system
        pass_filenames: false

      - id: tsc
        name: tsc
        entry: python pre-commit-npm.py run tsc
        types_or: [javascript, json]
        language: system
        pass_filenames: false

      - id: black
        name: black
        entry: poetry run black --config=pyproject.toml
        types_or: [ python, pyi ]
        language: system

      - id: isort
        name: isort
        entry: poetry run isort --sp=pyproject.toml
        types_or: [ python, pyi ]
        language: system

      - id: mypy
        name: mypy
        entry: poetry run mypy . --config-file=pyproject.toml
        types_or: [ python, pyi ]
        language: system
        pass_filenames: false

      - id: pylint
        name: pylint
        entry: poetry run pylint -j 0 --rcfile pyproject.toml
        types_or: [ python, pyi ]
        language: system
