name: 'Setup test environment'
description: 'Sets up Python, Poetry and dependencies'

inputs:
  python:
    description: 'Python version to use'
    default: 3.9.0
    required: false
  poetry:
    description: 'Poetry version to use'
    default: 1.1.12
    required: false

runs:
  using: "composite"

  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python }}

    - uses: snok/install-poetry@v1
      with:
        version: ${{ inputs.poetry }}
        virtualenvs-in-project: true

    - id: cached-poetry
      uses: actions/cache@v2
      with:
        path: .venv
        key: >
          ${{ hashFiles('pyproject.toml') }}-${{ hashFiles('poetry.lock') }}
          -${{ inputs.python }}-${{ inputs.poetry }}

    - if: steps.cached-poetry.outputs.cache-hit != 'true'
      run: |
        poetry lock --no-update
        poetry install --no-interaction
      shell: bash
