"""Add timestamps to tags

Revision ID: e33776b0b984
Revises: 20231002152120
Create Date: 2023-10-10 17:37:53.173181+01:00

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy import Text

import encord_active

# revision identifiers, used by Alembic.
revision = "20131010173753"
down_revision = "20231002152120"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project_tags", sa.Column("created_at", sa.TIMESTAMP(), nullable=True))
    op.add_column("project_tags", sa.Column("updated_at", sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_tags", "updated_at")
    op.drop_column("project_tags", "created_at")
    # ### end Alembic commands ###
