"""“migrate_video_colors”

Revision ID: 93edf437b8e0
Revises: bcfdfc2f498a
Create Date: 2023-08-09 16:10:08.930817+01:00

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "93edf437b8e0"
down_revision = "bcfdfc2f498a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("active_project_analytics_data", sa.Column("metric_video_red_density", sa.Float(), nullable=True))
    op.add_column("active_project_analytics_data", sa.Column("metric_video_green_density", sa.Float(), nullable=True))
    op.add_column("active_project_analytics_data", sa.Column("metric_video_blue_density", sa.Float(), nullable=True))
    op.create_index(
        "active_data_project_hash_metric_video_blue_density_index",
        "active_project_analytics_data",
        ["project_hash", "metric_video_blue_density"],
        unique=False,
    )
    op.create_index(
        "active_data_project_hash_metric_video_green_density_index",
        "active_project_analytics_data",
        ["project_hash", "metric_video_green_density"],
        unique=False,
    )
    op.create_index(
        "active_data_project_hash_metric_video_red_density_index",
        "active_project_analytics_data",
        ["project_hash", "metric_video_red_density"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("active_data_project_hash_metric_video_red_density_index", table_name="active_project_analytics_data")
    op.drop_index(
        "active_data_project_hash_metric_video_green_density_index", table_name="active_project_analytics_data"
    )
    op.drop_index(
        "active_data_project_hash_metric_video_blue_density_index", table_name="active_project_analytics_data"
    )
    op.drop_column("active_project_analytics_data", "metric_video_blue_density")
    op.drop_column("active_project_analytics_data", "metric_video_green_density")
    op.drop_column("active_project_analytics_data", "metric_video_red_density")
    # ### end Alembic commands ###
