"""“adds-simple-metrics-average-metrics”

Revision ID: ca5e32b270fa
Revises: bcfdfc2f498a
Create Date: 2023-08-10 16:06:48.254562+01:00

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "ca5e32b270fa"
down_revision = "bcfdfc2f498a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("active_project_analytics_data", sa.Column("metric_contrast_avg", sa.Float(), nullable=True))
    op.add_column("active_project_analytics_data", sa.Column("metric_blue_avg", sa.Float(), nullable=True))
    op.add_column("active_project_analytics_data", sa.Column("metric_green_avg", sa.Float(), nullable=True))
    op.add_column("active_project_analytics_data", sa.Column("metric_red_avg", sa.Float(), nullable=True))
    op.add_column("active_project_analytics_data", sa.Column("metric_sharpness_avg", sa.Float(), nullable=True))
    op.add_column("active_project_analytics_data", sa.Column("metric_brightness_avg", sa.Float(), nullable=True))
    op.create_index(
        "active_data_project_hash_metric_blue_avg_index",
        "active_project_analytics_data",
        ["project_hash", "metric_blue_avg"],
        unique=False,
    )
    op.create_index(
        "active_data_project_hash_metric_contrast_avg_index",
        "active_project_analytics_data",
        ["project_hash", "metric_contrast_avg"],
        unique=False,
    )
    op.create_index(
        "active_data_project_hash_metric_green_avg_index",
        "active_project_analytics_data",
        ["project_hash", "metric_green_avg"],
        unique=False,
    )
    op.create_index(
        "active_data_project_hash_metric_red_avg_index",
        "active_project_analytics_data",
        ["project_hash", "metric_red_avg"],
        unique=False,
    )
    op.create_index(
        "active_data_project_hash_metric_sharpness_avg_index",
        "active_project_analytics_data",
        ["project_hash", "metric_sharpness_avg"],
        unique=False,
    )
    op.create_index(
        "active_data_project_hash_metric_brightness_avg_index",
        "active_project_analytics_data",
        ["project_hash", "metric_brightness_avg"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("active_data_project_hash_metric_brightness_avg_index", table_name="active_project_analytics_data")
    op.drop_index("active_data_project_hash_metric_sharpness_avg_index", table_name="active_project_analytics_data")
    op.drop_index("active_data_project_hash_metric_red_avg_index", table_name="active_project_analytics_data")
    op.drop_index("active_data_project_hash_metric_green_avg_index", table_name="active_project_analytics_data")
    op.drop_index("active_data_project_hash_metric_contrast_avg_index", table_name="active_project_analytics_data")
    op.drop_index("active_data_project_hash_metric_blue_avg_index", table_name="active_project_analytics_data")
    op.drop_column("active_project_analytics_data", "metric_brightness_avg")
    op.drop_column("active_project_analytics_data", "metric_sharpness_avg")
    op.drop_column("active_project_analytics_data", "metric_red_avg")
    op.drop_column("active_project_analytics_data", "metric_green_avg")
    op.drop_column("active_project_analytics_data", "metric_blue_avg")
    op.drop_column("active_project_analytics_data", "metric_contrast_avg")
    # ### end Alembic commands ###
