"""metric_engine

Revision ID: ee71a9530e80
Revises: bcfdfc2f498a
Create Date: 2023-08-01 11:34:58.576639+01:00

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = "ee71a9530e80"
down_revision = "bcfdfc2f498a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands edited from alembic auto-generated commands ###
    op.drop_column("active_project_analytics_annotation", "embedding_clip")
    op.drop_column("active_project_analytics_annotation", "embedding_hu")
    op.drop_column("active_project_analytics_data_extra", "embedding_hu")
    op.add_column(
        "active_project_analytics_annotation_extra", sa.Column("derived_clip_nearest", sa.JSON(), nullable=True)
    )
    op.add_column("active_project_analytics_data_extra", sa.Column("derived_clip_nearest", sa.JSON(), nullable=True))
    # metric_label_duplicates => metric_max_iou (Annotation)
    op.drop_index(
        "active_label_project_hash_metric_label_duplicates_index", table_name="active_project_analytics_annotation"
    )
    with op.batch_alter_table('active_project_analytics_annotation') as bop:
        bop.alter_column(
            'metric_label_duplicates',
            nullable=True, new_column_name='metric_max_iou',
            existing_type=sa.Float()
        )
    op.create_index(
        "active_label_project_hash_metric_max_iou_index",
        "active_project_analytics_annotation",
        ["project_hash", "metric_max_iou"],
        unique=False,
    )
    # metric_label_duplicates => metric_max_iou (Prediction)
    with op.batch_alter_table('active_project_prediction_analytics') as bop:
        bop.alter_column(
            'metric_label_duplicates',
            nullable=True, new_column_name='metric_max_iou',
            existing_type=sa.Float()
        )
    with op.batch_alter_table('active_project_prediction_analytics_false_negatives') as bop:
        bop.alter_column(
            'metric_label_duplicates',
            nullable=True, new_column_name='metric_max_iou',
            existing_type=sa.Float()
        )
    # metric_image_singularity => metric_image_uniqueness
    op.add_column("active_project_analytics_data", sa.Column("metric_image_uniqueness", sa.Float(), nullable=True))
    op.drop_index("active_data_project_hash_metric_image_singularity_index", table_name="active_project_analytics_data")
    op.create_index(
        "active_data_project_hash_metric_image_uniqueness_index",
        "active_project_analytics_data",
        ["project_hash", "metric_image_uniqueness"],
        unique=False,
    )
    op.drop_column("active_project_analytics_data", "metric_image_singularity")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("active_project_analytics_annotation", sa.Column("embedding_hu", sa.BLOB(), nullable=True))
    op.add_column("active_project_analytics_annotation", sa.Column("embedding_clip", sa.BLOB(), nullable=True))
    op.add_column("active_project_analytics_data_extra", sa.Column("embedding_hu", sa.BLOB(), nullable=True))
    op.drop_column("active_project_analytics_data_extra", "derived_clip_nearest")
    op.drop_column("active_project_analytics_annotation_extra", "derived_clip_nearest")
    #  metric_max_iou => metric_label_duplicates (Annotation)
    op.drop_index("active_label_project_hash_metric_max_iou_index", table_name="active_project_analytics_annotation")
    with op.batch_alter_table('active_project_analytics_annotation') as bop:
        bop.alter_column(
            'metric_max_iou',
            nullable=True, new_column_name='metric_label_duplicates',
            existing_type=sa.FLOAT()
        )
    op.create_index(
        "active_label_project_hash_metric_label_duplicates_index",
        "active_project_analytics_annotation",
        ["project_hash", "metric_label_duplicates"],
        unique=False,
    )
    # metric_max_iou => metric_label_duplicates (Prediction)
    with op.batch_alter_table('active_project_prediction_analytics') as bop:
        bop.alter_column(
            'metric_max_iou',
            nullable=True, new_column_name='metric_label_duplicates',
            existing_type=sa.FLOAT()
        )
    with op.batch_alter_table('active_project_prediction_analytics_false_negatives') as bop:
        bop.alter_column(
            'metric_max_iou',
            nullable=True, new_column_name='metric_label_duplicates',
            existing_type=sa.FLOAT()
        )
    # metric_image_uniqueness => metric_image_singularity
    op.drop_index("active_data_project_hash_metric_image_uniqueness_index", table_name="active_project_analytics_data")
    with op.batch_alter_table('active_project_analytics_data') as bop:
        bop.alter_column(
            'metric_image_uniqueness',
            nullable=True, new_column_name='metric_image_singularity',
            existing_type=sa.FLOAT()
        )
    op.create_index(
        "active_data_project_hash_metric_image_singularity_index",
        "active_project_analytics_data",
        ["project_hash", "metric_image_singularity"],
        unique=False,
    )
    # ### end Alembic commands ###
