name: Build

on:
  workflow_dispatch:

concurrency:
  group: encord-active-${{ github.ref }}-build
  cancel-in-progress: true

jobs:
  build:
    name: Build Encord.Active
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.AUTOMATION_BOT_ACCESS_TOKEN }}
          ref: main

      - name: Build frontend
        uses: ./.github/actions/build-frontend

      - name: Setup root poetry environment
        uses: ./.github/actions/setup-root-poetry-environment

      - name: Build
        run: poetry build
