name: Build

on:
  workflow_dispatch:

concurrency:
  group: encord-active-${{ github.ref }}-build
  cancel-in-progress: true

jobs:
  build-frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.AUTOMATION_BOT_ACCESS_TOKEN }}
          ref: main

      - name: Build
        uses: ./.github/actions/build-frontend
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build-${{ github.sha }}
          path: src/encord_active/frontend/dist
          if-no-files-found: error

  build-package:
    needs: ["build-frontend"]
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.AUTOMATION_BOT_ACCESS_TOKEN }}
          ref: main

      - name: Download frontend build
        uses: actions/download-artifact@v3
        with:
          name: frontend-build-${{ github.sha }}
          path: src/encord_active/frontend/dist

      - name: Setup root poetry environment
        uses: ./.github/actions/setup-root-poetry-environment

      - name: Build
        run: poetry build
