name: Docs build, deploy

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
  release:
    types: [published]
  workflow_dispatch:

env:
  NODE_VERSION: 18
  SRC_FOLDER: docs
  BUILD_ARTIFACT_NAME: build_artifact
  BUILD_ARTIFACT_PATH: docs/build
concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: "docs/package-lock.json"

      - name: Install dependencies
        working-directory: ${{ env.SRC_FOLDER }}
        run: |
          npm ci

      - name: Build docs
        working-directory: ${{ env.SRC_FOLDER }}
        run: |
          npm run-script build

      - name: Upload build folder
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BUILD_ARTIFACT_NAME }}
          path: ${{ env.BUILD_ARTIFACT_PATH }}
          if-no-files-found: error
          retention-days: 1

  deploy:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.BUILD_ARTIFACT_NAME }}
          path: ${{ env.BUILD_ARTIFACT_PATH }}

      - name: Create deployment message
        id: vars
        run: |
          echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "message=$(git log -1 --format=%s | cut -c -64)" >> $GITHUB_OUTPUT

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:prod -m \"${{ steps.vars.outputs.sha }} ${{ steps.vars.outputs.message }}\"
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ENCORD_ACTIVE_FRONTEND }}
          PROJECT_PATH: ./${{ env.SRC_FOLDER }}

      - name: Trigger global docs rebuild
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{secrets.AUTOMATION_BOT_ACCESS_TOKEN}}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/encord-team/cord-docs/actions/workflows/docs-deploy.yml/dispatches \
          -d '{"ref": "main"}'
